# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e556fcaacd27e8007b8de186ee55c1b7933d777b7b6c1c7a768554dfa141302f6a16fef0f699d025b40bc51c08e04001cae4170d0aa8cc00bcc9cb9bc523fde8

test:
  secret_key_base: 3e05b56ba6ca38e0a9097ef9f3f32d233505f6bedcca4affe32498fe29811c44c069a7719af739645fded5968b1b11face7011a230fdc5b36c5086a13b8d20f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
